# CLion remote docker environment (How to build docker container, run and stop it)
#
# Build and run:
#   docker build -t clion/remote-alpine:1.0 -f Dockerfile-alpine .
#   docker run -d --cap-add sys_ptrace -p127.0.0.1:2222:22 clion/remote-alpine:1.0
#   ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:2222"
#
# stop:
#   docker stop clion_remote_env
#
# ssh credentials (test user):
#   root@root

FROM alpine:latest

RUN apk add --update openssh gcc g++ clang gdb cmake make ninja autoconf automake dos2unix tar rsync python3 \
  && rm  -rf /tmp/* /var/cache/apk/*

RUN echo "root:root" | chpasswd

RUN ( \
	echo 'PermitRootLogin yes'; \
	echo 'PasswordAuthentication yes'; \
	echo 'Subsystem sftp /usr/lib/ssh/sftp-server'; \
  ) > /etc/sshd_config_test_clion

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D", "-f", "/etc/sshd_config_test_clion"]